### <Auth>
GET http://localhost:8080/login

### 
POST http://localhost:8080/register
content-type: application/json

{
    "username": "robocon321",
    "password": "0123456789"
}

### 
POST http://localhost:8080/login
content-type: application/json

{
    "username": "robocon321",
    "password": "0123456789"
}

###
POST http://localhost:8080/loadUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIwMTYzODksImlhdCI6MTcwMjAwOTE4OX0.EQ28ya6ifq8T6wASxVHnjd9m9jB-W3IlFvXQdXvOUaM

### </Auth>