### <Auth>
GET http://localhost:8080/login

### 
POST http://localhost:8080/register
content-type: application/json

{
    "username": "robocon321c",
    "password": "0123456789"
}

### 
POST http://localhost:8080/login
content-type: application/json

{
    "username": "robocon321b",
    "password": "0123456789"
}

###
POST http://localhost:8080/loadUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjozNiwiZXhwIjoxNzA3NDc0MTg3LCJpYXQiOjE3MDc0NjY5ODd9.UEnVeai97FxMf5b8P-BbGYbwqf50Tf1Ww0Joo0fxZYI
### </Auth>