### <Auth>
GET http://localhost:8080/login

### 
POST http://localhost:8080/register
content-type: application/json

{
    "username": "robocon321",
    "password": "0123456789"
}

### 
POST http://localhost:8080/login
content-type: application/json

{
    "username": "robocon321",
    "password": "0123456789"
}

###
POST http://localhost:8080/loadUser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIwOTU2ODQsImlhdCI6MTcwMjA4ODQ4NH0.EiPpicKEQISQPXMeVf8L2zPXFmTbtpfcrU9eR4W-wJc

### </Auth>