###
POST http://localhost:8080/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDczMDI1MDcsImlhdCI6MTcwNzI5NTMwN30.FKdluRWxiPFjLfG43S2FAtiWBcWfqaLOJ4zT5vzMbrI

{
    "product_id": 1,
    "quantity": 2
}

###
DELETE http://localhost:8080/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDczMDI1MDcsImlhdCI6MTcwNzI5NTMwN30.FKdluRWxiPFjLfG43S2FAtiWBcWfqaLOJ4zT5vzMbrI

{
    "product_id": 1
}

###
PUT http://localhost:8080/cart/multi
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDczMDI1MDcsImlhdCI6MTcwNzI5NTMwN30.FKdluRWxiPFjLfG43S2FAtiWBcWfqaLOJ4zT5vzMbrI

[{
    "product_id": 1,
    "quantity": 10
}, {
    "product_id": 2,
    "quantity": 5    
}, {
    "product_id": 3,
    "quantity": 2    
}]