###
POST http://localhost:8080/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIxMDUxNzQsImlhdCI6MTcwMjA5Nzk3NH0.KzSYSs07iSHbTwNn3ibstCrbc1-kLfcz4J5HU4G64mU

{
    "product_id": 1,
    "quantity": 2
}

###
DELETE http://localhost:8080/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIwNjI2OTEsImlhdCI6MTcwMjA1NTQ5MX0.A7GX0OkXdk8Yzi2FnPDWBiRon1-iH_g5wFkWiMZYRg8

{
    "product_id": 10
}

###
PUT http://localhost:8080/cart/multi
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIxMjQxODAsImlhdCI6MTcwMjExNjk4MH0.ZYiAgXbUVDIqO_vKx5siLAeU1-zLRLLDTNJelrObhc0

[{
    "product_id": 1,
    "quantity": 10
}, {
    "product_id": 2,
    "quantity": 5    
}, {
    "product_id": 3,
    "quantity": 2    
}]