###
POST http://localhost:8080/wishlist
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDczNzMwMTcsImlhdCI6MTcwNzM2NTgxN30.WZqor2dnoNk2pv6alxDMZQIrRqbcGu5JnwgDySbDPYY

{
    "product_id": 10
}

###
DELETE http://localhost:8080/wishlist
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDczNzMwMTcsImlhdCI6MTcwNzM2NTgxN30.WZqor2dnoNk2pv6alxDMZQIrRqbcGu5JnwgDySbDPYY

{
    "product_id": 10
}
