###
POST http://localhost:8080/wishlist
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIwMzA5NjIsImlhdCI6MTcwMjAyMzc2Mn0.W27wHuG8pT6mqJVQxkNjbEuBwRjCEjRDvWxoMV5JZGI

{
    "product_id": 10
}

###
DELETE http://localhost:8080/wishlist
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxLCJleHAiOjE3MDIwMzA5NjIsImlhdCI6MTcwMjAyMzc2Mn0.W27wHuG8pT6mqJVQxkNjbEuBwRjCEjRDvWxoMV5JZGI

{
    "product_id": 10
}
